version : '3'

services :
  db :
    container_name : 'amornrada-postgres'
    ports:
      - 54321:5432
    environment :
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image : 'postgres:14.4'
    restart : 'unless-stopped'
  pgadmin :
    container_name : 'amornrada-pgadmin'
    ports:
      - 8080:80
    environment :
      - PGADMIN_DEFAULT_EMAIL=${PG_EMATL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASS}
    image : 'dpage/pgadmin4:latest'
    restart : 'unless-stopped'
  strapi : 
    container_name : 'amornrada-strapi'
    ports:
      - 1337:1337
    environment :
      - DATABASE_CLIENT=${STRAPI_CLIENT}
      - DATABASE_HOST=${STRAPI_HOST}
      - DATABASE_PORT=${STRAPI_PORT}
      - DATABASE_NAME=${STRAPI_NAME}
      - DATABASE_USERNAME=${STRAPI_USERNAME}
      - DATABASE_PASSWORD=${STRAPI_PASSWORD}
      - DATABASE_SSL=${STRAPI_SSL}
    image : 'naskio/strapi:latest'
    restart : 'unless-stopped'
